//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoNetConsole {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IPLists {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IPLists() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeoNetConsole.IPLists", typeof(IPLists).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 212.149.105.71
        ///68.0.26.102
        ///62.212.74.140
        ///61.134.26.42
        ///24.46.150.29
        ///211.90.51.18
        ///209.52.239.105
        ///65.124.32.5
        ///209.52.239.105
        ///66.28.71.23
        ///62.80.111.98
        ///64.202.96.66
        ///62.93.205.159
        ///213.231.14.30
        ///67.92.214.194
        ///202.102.29.161
        ///213.202.203.43
        ///200.180.11.120
        ///202.151.228.85
        ///80.163.202.190
        ///61.136.221.28
        ///146.20.88.84
        ///202.159.181.123
        ///194.242.45.9
        ///203.144.107.5
        ///203.59.9.6
        ///203.59.9.6
        ///195.54.109.212
        ///195.54.109.212
        ///217.17.31.12
        ///24.199.176.227
        ///68.4.175.163
        ///209.220.161.109
        ///213.114.138.170
        ///157.15 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IP4List {
            get {
                return ResourceManager.GetString("IP4List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 216.236.135.152,US
        ///192.106.51.100,IT
        ///147.251.48.1,CZ
        ///203.174.65.12,JP
        ///212.208.74.140,FR
        ///200.219.192.106,BR
        ///134.102.101.18,DE
        ///193.75.148.28,BE
        ///194.244.83.2,IT
        ///203.15.106.23,AU
        ///196.31.1.1,ZA,ZAF
        ///151.28.39.114,IT
        ///151.38.70.94,IT
        ///193.56.4.124,FR
        ///195.142.146.198,TR
        ///211.232.0.0,KR
        ///211.240.0.0,KR
        ///193.194.4.0,MA
        ///139.20.112.104,DE
        ///139.20.112.3,DE
        ///145.236.125.211,HU
        ///149.225.169.61,DE
        ///151.17.191.46,IT
        ///151.24.176.194,IT
        ///151.25.8.136,IT
        ///151.26.146.192,IT
        ///151.26.153.66,IT
        ///151.26.167.71,IT
        ///151. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IP4Test {
            get {
                return ResourceManager.GetString("IP4Test", resourceCulture);
            }
        }
    }
}
